Resources:
  CyGetData:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: cy-get-data.handler
      Role: 'arn:aws:iam::675207449389:role/cy-get-scan-item-role'
      Code:
        S3Bucket: mgabeeireland
        S3Key: cy-get-data.zip
      Runtime: nodejs6.10
      Timeout: '25'
