Resources:
  CyGetData:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: cf-cy-get-data
      Handler: cy-get-data.handler
      Role: !ImportValue CfCyGetDataRoleArn
      Code:
        S3Bucket: mgabeeireland
        S3Key: cy-get-data.zip
      Runtime: nodejs6.10
      Timeout: '25'
